# Generated by Django 2.2.6 on 2019-11-19 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsEmailTask',
            fields=[
                ('baseemailtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseEmailTask')),
                ('comments', models.ManyToManyField(to='main.Comment')),
            ],
            bases=('main.baseemailtask',),
        ),
    ]
