# Generated by Django 2.2.6 on 2019-11-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_commentsemailtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentsEmailTask',
        ),
    ]
