# Generated by Django 2.1.3 on 2019-02-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190213_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistprofile',
            options={'permissions': (('create_artworks', 'can download new artworks'), ('become_artist', 'was invited and can registrate as artist'))},
        ),
    ]
