# Generated by Django 2.1.3 on 2019-02-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190215_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistprofile',
            options={},
        ),
    ]
