# Generated by Django 2.1.3 on 2019-02-16 12:02
from __future__ import unicode_literals 
from django.db import migrations

def add_permissions(apps, schema_editor):
    pass


def remove_permissions(apps, schema_editor):
    """Reverse the above additions of permissions."""
    ContentType = apps.get_model('contenttypes.ContentType')
    Permission = apps.get_model('auth.Permission')
    content_type = ContentType.objects.get(
        model='artist profile',
        app_label='main',
    )
    # This cascades to Group
    Permission.objects.filter(
        content_type=content_type,
        codename__in=('create_artworks', 'become_artist'),
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190215_1155'),
    ]

    operations = [
    ]
