# Generated by Django 2.1.3 on 2019-03-18 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20190216_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=250)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='author',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='id',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='name',
        ),
        migrations.AddField(
            model_name='artwork',
            name='publication_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Publication'),
            preserve_default=False,
        ),
    ]
