# Generated by Django 2.1.3 on 2019-03-20 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20190319_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='subs_count',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
