# Generated by Django 2.1.3 on 2019-05-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190320_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Publication')),
                ('desc', models.TextField(default='no desc')),
                ('text', models.TextField(default='no text')),
            ],
            bases=('main.publication',),
        ),
    ]
