# Generated by Django 2.1.3 on 2019-05-04 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
