# Generated by Django 2.1.3 on 2019-05-06 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_comment_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
