# Generated by Django 2.1.3 on 2019-05-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190506_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.AddField(
            model_name='tag',
            name='publications',
            field=models.ManyToManyField(to='main.Publication'),
        ),
    ]
