# Generated by Django 2.1.3 on 2019-09-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190821_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='date',
            new_name='datetime',
        ),
    ]
