# Generated by Django 2.1.3 on 2019-09-25 06:39

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190905_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=main.models.ArtistProfile.avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to=main.models.Artwork.upload_path),
        ),
    ]
