# Generated by Django 2.1.3 on 2019-11-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_profilesettings_usersettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesettings',
            old_name='artwork_comments_update_notifications',
            new_name='publication_comments_update_notifications',
        ),
    ]
