# Generated by Django 2.1.3 on 2019-11-17 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0032_auto_20191104_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEmailTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsEmailTask',
            fields=[
                ('baseemailtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseEmailTask')),
                ('comments', models.ManyToManyField(to='main.Comment')),
            ],
            bases=('main.baseemailtask',),
        ),
        migrations.CreateModel(
            name='FeedUpdateEmailTask',
            fields=[
                ('baseemailtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseEmailTask')),
                ('publications', models.ManyToManyField(to='main.Publication')),
            ],
            bases=('main.baseemailtask',),
        ),
        migrations.CreateModel(
            name='SubscribersEmailTask',
            fields=[
                ('baseemailtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseEmailTask')),
                ('subscribers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=('main.baseemailtask',),
        ),
        migrations.AddField(
            model_name='baseemailtask',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
