# Generated by Django 2.1.3 on 2019-11-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20191117_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentsEmailTask',
        ),
        migrations.DeleteModel(
            name='SubscribersEmailTask',
        ),
    ]
