# Generated by Django 2.1.3 on 2019-12-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_commentsemailtask'),
        ('main', '0034_auto_20191119_1945'),
    ]

    operations = [
    ]
