# Generated by Django 2.2.6 on 2019-11-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_commentsemailtask'),
        ('main', '0034_auto_20191119_1945'),
    ]

    operations = [
    ]
