# Generated by Django 2.1.3 on 2019-12-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
