# Generated by Django 2.1.3 on 2019-12-18 17:35

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20191218_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='avatar',
            field=models.ImageField(default='static/fav.png', upload_to=main.models.ArtistProfile.avatar_upload_path),
        ),
    ]
