# Generated by Django 2.1.3 on 2019-12-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20191218_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
