# Generated by Django 2.1.3 on 2019-12-18 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20191218_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
