# Generated by Django 2.1.3 on 2019-12-18 20:22

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20191218_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to=main.models.ArtistProfile.avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ArtistProfile'),
        ),
    ]
